name: agenpo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  flutter_launcher_icons: ^0.11.0

  path_provider: any
  country_code_picker: ^2.0.2
  intl_phone_number_input: ^0.7.0+2
  smooth_page_indicator: ^1.0.0+2
  timeago: ^3.3.0
  flutter_spinkit: ^5.1.0
  flutter_html: any
  money_formatter: ^0.0.3
  google_maps_flutter: any
  address_search_field: ^5.0.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  uuid: ^3.0.7
  get: ^4.6.5
  file_picker: ^5.2.5
  libphonenumber:

  get_it:
  flutter_bloc:
  equatable:
  pedantic:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http:
  intl:
  flutter_svg:
  cached_network_image:
  permission_handler:
  image_picker:
  another_flushbar: any
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/img/ic_launcher.jpg"
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/lang/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/data/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
